const ACCOUNT_ALREADY_EXISTS = 'ACCOUNT_ALREADY_EXISTS';
const PASSWORD_ERROR = 'PASSWORD_ERROR';
const THE_LACK_OF_PASSWORD = 'THE_LACK_OF_PASSWORD';

module.exports = {
	ACCOUNT_ALREADY_EXISTS,
	PASSWORD_ERROR,
	THE_LACK_OF_PASSWORD
}